### PR TITLE
Added FPGA check

### PR DESCRIPTION
**Pull request by Keigun-Spark**
Added FPGA check to quit script if bootloader updated failed and deleted the FPGA firmware.
Added forum contact details of myself so users can reach out.

Added snipped of faultlog which possibly lead to the FPGA firmware missing.

Added FPGA firmware file to ignore file.

### CODE REVIEW

**Comment by lgbeno** [comment]
Thanks for this, one other change to note:

We need to be sure that the bootloader code is updated before the HWID change.  Some older versions of the bootloader do not know what to do with the newer hardware IDs that we are writing into the device.

FPGA related changes are good though!

**Comment by Keigun-Spark** [comment]
Do you have any specific bootloader version and below or just update the bootloader before the HWID in general?

**Comment by Keigun-Spark** [comment]
Changed order of update when old HWID is detected:
> Check HWID
> Check firmware
> Check bootloader
> If bootloader correct -> continue HWID update

> If HWID is not the old one nor the new one the script behaves as before by aborting.

> Radio update is only possible once the HWID is updated, which is just as before after the firmware and bootloader are updated.

**Comment by lgbeno** [comment]
I would say to just update the bootloader in general but the HWID should be from a list of "approved" HWIDs before the Bootloader is updated.

If HWID begins with 0xF0 or 0xF1 then:
1) Update Bootloader
2) Update HWID to 0xF1040009
3) Check/Update Application
4) Check/Update Radio
5) Check/Update FPGA

**Comment by Keigun-Spark** [comment]
Removed old flowchart from comment

**Comment by Keigun-Spark** [comment]
New flowchart with FPGA update.

Flowchart

**Comment by lgbeno** [comment]
Thanks @Keigun-Spark appreciate your continued work on this!

**Pull request merged**
