### PR TITLE
Edit of run_hwid_check.bat

### PR DESCRIPTION
**Pull request by Keigun-Spark**
**Major changes:**
Added firmware update function.
Added stops for previously unexpected conditions.
Changed order of functions so HWID always has to match before further updates.

**Minor changes:**
Cleaned code.
Changed code readability and order.

### CODE REVIEW

**Comment by Keigun-Spark** [comment]
Current bootloader version of all trackers I have is v1637337510. The script checks for a bootloader version of **1629157907**, which older(?).

**Comment by Keigun-Spark** [comment]
To note, the firmware function is checking for the firmware currently found in the SteamVR folder. That version is 1632556731. The script checks for said version. If the device version is older than that it updates with the locally stored file "tundra-tracker_application_v1632556731.fw".

**Comment by Keigun-Spark** [comment]
Updated script only checks if bootloader is 1622649182 or 1629157907. If it is 1622649182 it gets updated. Everything else gets ignored and the script gets stopped.

**Comment by Keigun-Spark** [comment]
**Major changes:**
Added check for amount of connected devices.
Made the script exit after pressing enter.
Changed timings for use with slow USB hubs.

**Minor changes:**
Added comments.

**Comment by lgbeno** [comment]
Thank you for making these edits!

As I was saying on the the forum, I don't know how I feel about the tool flashing firmware into the tracker.  For the purpose that you have outlined, I think that it is good however I wouldn't want this to become the main firmware flashing tool.

I always get worried about customers flashing firmware into their index and breaking it.

I'll give the merge a try and we can evaluate long term

**Comment by Keigun-Spark** [comment]
Flashing the firmware directly does pose a risk. As noted in line 94 it is a quick change to just verify that a minimum firmware level is reached before continuing further on so just the most outdated firmware gets updated, or to just end the script at that point and ask them to update the firmware via SteamVR before continuing. I just don't know which minimum firmware level would be save.

**Comment by lgbeno** [comment]
My worry is mainly about flashing firmware into a device with a HWID that is not supported.  The script is actually pretty safe from this perspective.  Unfortunately the consequences of someone making a mistake are really unfortunate too.  If you strategically hit ctrl+C at jus thte right time the batch file may just skip a step instead of actually executing the check I think.

**Pull request merged**
